---
  - name: Build a parity docker image
    hosts: local
    connection: local
    gather_facts: False
    tags: build
    vars:
      region: us-west-2

    tasks:
    
      - name: install the latest version of git
        become: yes
        yum:
          name: git
          state: latest
        tags:
          - deps
    
      - name: install the latest version of docker
        become: yes
        yum:
          name: docker
          state: latest
        tags:
          - deps
    
      - name: install the latest version of awscli
        become: yes
        yum:
          name: awscli
          state: latest
        tags:
          - deps
    
      - name: install the latest version of python-docker-py
        become: yes
        yum:
          name: python-docker-py
          state: latest
        tags:
          - deps
          
      - name: Get parity sources
        git:
          repo: 'https://github.com/paritytech/parity.git'
          dest: /home/centos/git
          version: v1.11.0-ci0
        tags:
          - source
  
      - name: get docker ecr creds
        shell: "aws ecr get-authorization-token --region {{ region }} --query 'authorizationData[].authorizationToken' --output text | base64 --decode | cut -d: -f2"
        register: ecr_password
                
      - name: Log into private registry
        docker_login:
          registry_url: https://838410721998.dkr.ecr.us-west-2.amazonaws.com
          username: AWS
          password: "{{ ecr_password }}"
          tls_verify: yes
          reauthorize: yes
        tags:
          - credentials
          
      - name: docker up
        service:
          name: docker
          status: started
        tags:
          - deps
                    
      - name: Build parity and with buildargs
        docker_image:
           path: /home/centos/git/parity/docker/centos/
           name: 838410721998.dkr.ecr.us-west-2.amazonaws.com/test
           tag: latest
           buildargs:
             tag: paritytech/parity:v1.11.0-ci0