---
  - name: Install Masters Playbook
    hosts: k8s-masters
    connection: ssh
    gather_facts: False
    tags: installation
    
    tasks:
   
    - atomic_container:
        name: kube-apiserver
        image: registry.centos.org/centos/kubernetes-sig-apiserver:latest
        backend: docker
        state: latest
        system: True
   
    - atomic_container:
        name: kube-scheduler
        image: registry.centos.org/centos/kube-sig-scheduler:latest
        backend: docker
        state: latest
        system: True
   
    - atomic_container:
        name: kube-controller-manager
        image: registry.centos.org/centos/kubernetes-sig-controller-manager:latest
        backend: docker
        state: latest
        system: True

           
    